FROM golang:1.24-alpine AS builder


#adding client conf
ARG branch
ENV env $branch

WORKDIR /app

RUN apk add --no-cache tzdata bash 

#ini buat nge download library/dependencies
COPY go.mod .
RUN go mod download all

#adding client conf
COPY . .


#gk punya check environmentnya
# RUN chmod +x ./deploy/check-env.sh
# RUN /bin/bash ./deploy/check-env.sh


#build binary file
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix nocgo -o go-binary .






FROM alpine:latest

WORKDIR /app


RUN apk add --no-cache tzdata bash && \
    addgroup -S nonroot && \
    adduser -S nonroot -G nonroot

#ngeset time zone
COPY --from=builder /usr/share/zoneinfo/Asia/Jakarta /etc/share/zoneInfo/Asia/Jakarta
ENV TZ=Asia/Jakarta

#cp bin file yang udah dibuat diatas
COPY --from=builder /app/go-binary /app/ 

#nambah 1 buat nyesuai dgn codingan
COPY --from=builder /app/XamppDefault /app/XamppDefault 


#gk ada environment
# COPY --from=builder /app/.env /app/ 

#pake user non root 
RUN chown -R nonroot:nonroot /app


EXPOSE 10000

#make user non root 
USER nonroot:nonroot


ENTRYPOINT [ "/app/go-binary" ]

# ENTRYPOINT ["/bin/sh", "-c" , "/app/go-binary" ]






