apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\dimas.kurniawan.IT0100218137\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: db
  name: db
spec:
  ports:
    - name: "9926"
      port: 9926
      targetPort: 3306
  selector:
    io.kompose.service: db
