apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\dimas.kurniawan.IT0100218137\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: phpmyadmin
  name: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: phpmyadmin
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\dimas.kurniawan.IT0100218137\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: phpmyadmin
    spec:
      containers:
        - env:
            - name: PMA_HOST
              value: db
            - name: PMA_PASSWORD
              value: root
            - name: PMA_USER
              value: root
            - name: UPLOAD_LIMIT
              value: 1G
          image: phpmyadmin/phpmyadmin:5.1.3
          name: skripsi-phpmyadmin
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
