apiVersion: v1
kind: Pod
metadata:
  name: testgolang
spec:
  containers:
    - name: testgolang
      image: sha256:608a874edd39082b90074f9bc52d83a6ea40d3ca3cd69176483318453b399499
      ports:
        - containerPort: 10000