apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-deployment
  namespace: testgolang
  # labels:
    # dynatrace.com/inject: "false"
  annotations:
    desc:  testing integration golang with dynatrace





spec:
  replicas: 2
  selector:
    matchLabels:
      name: test_go
  template:
    metadata:
      name: golang_replica #replica name
      # namespace: TestingGo ##willnot work
      labels:
        name: test_go
        dynatrace: enabled
      annotations:
        # dynatrace.com/inject: "false"
        dynatrace: enabled
    spec:
      containers:
      - name: testgolang-container
        image: dimas519/testing_golang_for_oneagent_dt:2.0
        # imagePullPolicy: Never
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1.5Gi
        ports:
        - containerPort: 30000
      

---

apiVersion: v1
kind: Service
metadata:
  name: test-golang-service
  namespace: testgolang
spec:
  type: LoadBalancer
  selector:
    name: test_go
  ports:
    - port: 30001
      targetPort: 10000
      # nodePort: 30000