apiVersion: v1
kind: Pod
metadata:
  name: testgolang
  namespace: testns
  labels:
    version: "1.0"
    app: testingGolangwithdt
  annotations:
    test: aadf dafdf adfdsa
spec:
  containers:
    - name: testgolang
      image: sha256:608a874edd39082b90074f9bc52d83a6ea40d3ca3cd69176483318453b399499
      ports:
        - containerPort: 10000
      livenessProbe:
        httpGet:
          path: /checkIndex
          port: 10000
        initialDelaySeconds: 30
        periodSeconds: 10
        timeoutSeconds: 1
        successThreshold: 1
        failureThreshold: 3